# Generated by Django 5.0.6 on 2024-06-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersubscription',
            name='plan_end_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='plan_start_datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
