# Generated by Django 5.0.6 on 2024-06-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='code',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
